query teacherQuery($id: ID!) {
  teacher(id: $id) {
    id
    name
    caption
    description
    image {
      url
    }
  },
  teachers {
    id
    name
    caption
    image {
      url
    }
  }
}