query mainQuery {
  galleries {
    id
    name
    image {
      url
      id
    }
  }
  schedules {
    id
    day 
    description
  }
  teachers {
    id
    name
    caption
    image {
      url
    }
  }
  prices {
    id
    price
    name
    entries {
      id
      entry
    }
  }
  facilities {
    id
    entry
    caption
  }
}