query mainQuery {
  galleries(sort: "createdAt:asc") {
    name
    id
    image {
      url
    }
  }
  schedules {
    id
    day
    name
    description
  }
  teachers {
    id
    name
    caption
    image {
      url
    }
  }
  prices {
    id
    price
    name
    entries {
      id
      entry
    }
  }
  events {
    id
    name
    date
    description
  }
  opinions {
    id
    body 
    name
    caption
    image {
      url
    }
  }
}